/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedScalesRouteImport } from './routes/_authenticated.scales'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated.practice'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated.library'
import { Route as AuthenticatedTabsSongIdRouteImport } from './routes/_authenticated.tabs.$songId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScalesRoute = AuthenticatedScalesRouteImport.update({
  id: '/scales',
  path: '/scales',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTabsSongIdRoute = AuthenticatedTabsSongIdRouteImport.update({
  id: '/tabs/$songId',
  path: '/tabs/$songId',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/scales': typeof AuthenticatedScalesRoute
  '/tabs/$songId': typeof AuthenticatedTabsSongIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/scales': typeof AuthenticatedScalesRoute
  '/tabs/$songId': typeof AuthenticatedTabsSongIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/scales': typeof AuthenticatedScalesRoute
  '/_authenticated/tabs/$songId': typeof AuthenticatedTabsSongIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/library'
    | '/practice'
    | '/profile'
    | '/scales'
    | '/tabs/$songId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/library'
    | '/practice'
    | '/profile'
    | '/scales'
    | '/tabs/$songId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/library'
    | '/_authenticated/practice'
    | '/_authenticated/profile'
    | '/_authenticated/scales'
    | '/_authenticated/tabs/$songId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scales': {
      id: '/_authenticated/scales'
      path: '/scales'
      fullPath: '/scales'
      preLoaderRoute: typeof AuthenticatedScalesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tabs/$songId': {
      id: '/_authenticated/tabs/$songId'
      path: '/tabs/$songId'
      fullPath: '/tabs/$songId'
      preLoaderRoute: typeof AuthenticatedTabsSongIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedScalesRoute: typeof AuthenticatedScalesRoute
  AuthenticatedTabsSongIdRoute: typeof AuthenticatedTabsSongIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedScalesRoute: AuthenticatedScalesRoute,
  AuthenticatedTabsSongIdRoute: AuthenticatedTabsSongIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
